# Generated by Django 5.1.7 on 2025-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_name', models.CharField(max_length=255)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_location_name', models.CharField(max_length=255)),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('current_cycle_used', models.FloatField()),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('log_pdf', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
