# Generated by Django 5.1.7 on 2025-03-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='log_pdf',
            field=models.FileField(blank=True, null=True, upload_to='logs/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(null=True),
        ),
    ]
